name: Job Scan Pipeline

on:
  workflow_dispatch:

jobs:
  job-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Initialize
        run: echo 'job scanning is running'

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install \
            jobspy \
            jobsparser \
            python-jobspy 

      - name: Execute job script
        run: bash scripts/job.sh

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.25.1

      - name: Build Go project
        run: go build -o ./bin/out ./cmd/.

      - name: Run Go project to generate HTML
        run: ./bin/out


      - name: Commit HTML to view branch
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Check if branch exists
          if git show-ref --quiet refs/heads/view; then
            git checkout view
          else
            git checkout --orphan view
            git rm -rf .
          fi

          # Copy generated HTML
          cp -r static/html/* .

          git add .
          git commit -m "Update static HTML from job scan"
          git push origin view --force


      - name: list scripts
        run: ls scripts/job.sh

      - name: list
        run: ls .

      - name: Publish job results
        uses: actions/upload-artifact@v4
        with:
          name: job_results
          path: job_results
          retention-days: 14
