name: Job Scan Pipeline

on:
  schedule:
    - cron: "0 */24 * * *"
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  job-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Initialize
        run: echo 'job scanning is running'

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install \
            jobspy \
            jobsparser \
            python-jobspy 

      - name: Run job scan (Berlin only)
        env:
          PROXY_ADDRESS: ${{ secrets.PROXY_ADDRESS }}
        run: |
          mkdir -p job_results
          
          echo ">>> Running jobsparser for Berlin"
          export HTTP_PROXY="http://mili:2rnUhgD2jO2uQAWm0aW1R8YQ@192.227.165.177:4410"
          export HTTPS_PROXY="http://mili:2rnUhgD2jO2uQAWm0aW1R8YQ@192.227.165.177:4410"
          export http_proxy="http://mili:2rnUhgD2jO2uQAWm0aW1R8YQ@192.227.165.177:4410"
          export https_proxy="http://mili:2rnUhgD2jO2uQAWm0aW1R8YQ@192.227.165.177:4410"
    
          jobsparser \
            --search-term '"Golang Developer" OR "Go Developer" OR "Backend Golang Developer" OR "Backend Engineer Go" OR "Software Engineer Go"' \
            --location "Berlin" \
            --site linkedin \
            --results-wanted 300 \
            --distance 50 \
            --job-type fulltime \
            --fetch-description \
            --hours-old 72 \
            --max-retries 0 \
            --output-dir "job_results" \
            --proxies "http://mili:2rnUhgD2jO2uQAWm0aW1R8YQ@192.227.165.177:4410"
    

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.25.1

      - name: Build Go project
        run: go build -o ./bin/out ./cmd/.

      - name: Run Go project to generate HTML
        run: ./bin/out

      - name: Commit HTML to view branch
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          # Check if branch exists
          if git show-ref --quiet refs/heads/view; then
            git checkout view
          else
            git checkout --orphan view
            git rm -rf .
          fi
          
          echo -e "bin/\nstatic/\njob_results/" > .gitignore
          echo '<!DOCTYPE html><html><head><meta http-equiv="refresh" content="0; url=list1.html"></head><body></body></html>' > index.html
          
          cp -r static/html/* .
          
          git add .
          git commit -m "Update static HTML from job scan"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git view --force

      - name: list
        run: ls .

      - name: Publish job results
        uses: actions/upload-artifact@v4
        with:
          name: job_results
          path: job_results
          retention-days: 14
